### PR TITLE
GHOST Apply enum

### PR DESCRIPTION
**Pull request by cquiroz**
This PR adds enum entries for GHOST apply.
I'm fairly certain these will change soon but I need the code update to continue working on the seqexec

### CODE REVIEW

**Comment by tpolecat** [comment]
Are you sure this includes everything? I don't see the new enumdef.

**Comment by cquiroz** [comment]
These are new entries to the `GiapiStatusApply` enum

**Comment by tpolecat** [comment]
That's generated code isn't it?

**Comment by cquiroz** [comment]
Yes it is, out of the table entries

**Comment by tpolecat** [comment]
Oh i gotcha, all you did was add new entries. Sorry for the confusion.

**Pull request merged**
